// Role-based permission matrix — mirrors server ROLE_PERMS in collateral-api/src/middleware/auth.js.
// Server is authoritative; client values must track server keys so UI gates line up with API gates.

export const ROLE_PERMS = {
  "Treasury Manager": {
    canCreateRepo:        true,
    canCloseRepo:         true,
    canRolloverRepo:      true,
    canUpdateRepo:        true,
    canApproveTopUp:      false,
    canSubstitute:        true,
    canAdvanceSettlement: false,
    canImportAssets:      false,
    canUpdateAsset:       false,
    canExport:            true,
    readOnly:             false,
    canEditHaircuts:      false,
    canEditCoverage:      true,
    canEditRiskParams:    false,
    canManageAgreements:  true,
    canIssueCall:         false,
    canRespondCall:       false,
    canOpenDispute:       false,
    canResolveDispute:    false,
    canApproveFourEyes:   false,
    canCancelCall:        true,
    canExportAudit:       false,
    description:          "Full trade lifecycle authority. Manages collateral agreements. Approves and executes substitutions.",
  },
  "Collateral Manager": {
    canCreateRepo:        false,
    canCloseRepo:         false,
    canRolloverRepo:      false,
    canUpdateRepo:        true,
    canApproveTopUp:      true,
    canSubstitute:        true,
    canAdvanceSettlement: false,
    canImportAssets:      true,
    canUpdateAsset:       true,
    canExport:            true,
    readOnly:             false,
    canEditHaircuts:      true,
    canEditCoverage:      false,
    canEditRiskParams:    false,
    canManageAgreements:  false,
    canIssueCall:         true,
    canRespondCall:       true,
    canOpenDispute:       true,
    canResolveDispute:    false,
    canApproveFourEyes:   false,
    canCancelCall:        false,
    canExportAudit:       false,
    description:          "Issues and responds to margin calls, manages top-ups and substitutions, opens disputes.",
  },
  "Operations Analyst": {
    canCreateRepo:        false,
    canCloseRepo:         false,
    canRolloverRepo:      false,
    canUpdateRepo:        false,
    canApproveTopUp:      false,
    canSubstitute:        false,
    canAdvanceSettlement: true,
    canImportAssets:      false,
    canUpdateAsset:       false,
    canExport:            true,
    readOnly:             false,
    canEditHaircuts:      false,
    canEditCoverage:      false,
    canEditRiskParams:    false,
    canManageAgreements:  false,
    canIssueCall:         false,
    canRespondCall:       true,
    canOpenDispute:       false,
    canResolveDispute:    false,
    canApproveFourEyes:   false,
    canCancelCall:        false,
    canExportAudit:       false,
    description:          "Advances settlement instructions and confirms deliveries. Read-only for trade and credit decisions.",
  },
  "Risk Reviewer": {
    canCreateRepo:        false,
    canCloseRepo:         false,
    canRolloverRepo:      false,
    canUpdateRepo:        false,
    canApproveTopUp:      false,
    canSubstitute:        false,
    canAdvanceSettlement: false,
    canImportAssets:      false,
    canUpdateAsset:       false,
    canExport:            true,
    readOnly:             true,
    canEditHaircuts:      false,
    canEditCoverage:      false,
    canEditRiskParams:    true,
    canManageAgreements:  false,
    canIssueCall:         false,
    canRespondCall:       false,
    canOpenDispute:       false,
    canResolveDispute:    false,
    canApproveFourEyes:   false,
    canCancelCall:        false,
    canExportAudit:       true,
    description:          "Read-only access across the book. Exports audit trails for regulators.",
  },
  "Credit Approver": {
    canCreateRepo:        false,
    canCloseRepo:         false,
    canRolloverRepo:      false,
    canUpdateRepo:        false,
    canApproveTopUp:      false,
    canSubstitute:        false,
    canAdvanceSettlement: false,
    canImportAssets:      false,
    canUpdateAsset:       false,
    canExport:            false,
    readOnly:             false,
    canEditHaircuts:      false,
    canEditCoverage:      false,
    canEditRiskParams:    false,
    canManageAgreements:  false,
    canIssueCall:         false,
    canRespondCall:       false,
    canOpenDispute:       false,
    canResolveDispute:    true,
    canApproveFourEyes:   true,
    canCancelCall:        false,
    canExportAudit:       false,
    description:          "Second pair of eyes. Grants or rejects margin-call actions above the agreement's four-eyes threshold.",
  },
};

export function getPermissions(role) {
  return ROLE_PERMS[role] ?? ROLE_PERMS["Risk Reviewer"];
}
